FROM alpine:3.10

# Copy from https://github.com/jboss-dockerfiles/keycloak/blob/6.0.1/server/Dockerfile
ENV KEYCLOAK_VERSION 6.0.1
ARG KEYCLOAK_DIST=https://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

RUN apk add --no-cache --virtual .build-deps curl \
    && mkdir -p /opt/jboss \
    && cd /opt/jboss/ \
    && curl -L $KEYCLOAK_DIST | tar zx \
    && mv /opt/jboss/keycloak-?.?.?* /opt/jboss/keycloak \
    && apk del --purge .build-deps

