FROM wadahiro/keycloak as kc

FROM wadahiro/openjdk13ea

COPY --from=kc --chown=1000:1000 /opt/jboss /opt/jboss

ENV JBOSS_HOME /opt/jboss/keycloak
ENV PROXY_ADDRESS_FORWARDING false

ENV JAVA_TOOL_OPTIONS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

EXPOSE 8080
EXPOSE 8443

USER 1000

RUN /bin/sh -c '/opt/jboss/keycloak/bin/standalone.sh &' ; sleep 60 ; ps aux | grep java | grep -v grep | awk '{print $1}' | xargs kill -1

ENTRYPOINT [ "/opt/jboss/keycloak/bin/standalone.sh" ]
CMD ["-b", "0.0.0.0"]

