FROM wadahiro/cl4cds as cl4cds 

FROM wadahiro/openjdk13ea-keycloak-spring-boot

COPY --from=cl4cds /cl4cds/src/classes/*.jar /opt/cl4cds.jar 

USER root
RUN mkdir -p /javasharedresources && chown 1000:1000 /javasharedresources 
USER 1000

RUN env JAVA_TOOL_OPTIONS="-Xlog:class+load=debug:file=/javasharedresources/keycloak.classtrace" /bin/sh -c 'java -jar /opt/keycloak.jar &' ; sleep 50 ; ps aux | grep java | grep -v grep | awk '{print $1}' | xargs kill -1

RUN java -jar /opt/cl4cds.jar /javasharedresources/keycloak.classtrace /javasharedresources/keycloak.cls

RUN env JAVA_TOOL_OPTIONS="-Xshare:dump -XX:SharedClassListFile=/javasharedresources/keycloak.cls -XX:SharedArchiveFile=/javasharedresources/archive.jsa" java -jar /opt/keycloak.jar

ENV JAVA_TOOL_OPTIONS="-XX:SharedArchiveFile=/javasharedresources/archive.jsa -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

ENV JAVA_TOOL_OPTIONS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "java", "-jar", "/opt/keycloak.jar" ]

