FROM wadahiro/keycloak-spring-boot as kc

FROM wadahiro/openjdk12-openj9

ARG JAR=spring-boot-keycloak-server-example-undertow-0.0.9.BUILD-SNAPSHOT.jar

COPY --from=kc --chown=1000:1000 /build/spring-boot-keycloak-server-example/target/$JAR /opt/

RUN mkdir -p /javasharedresources && chown 1000.1000 /javasharedresources
RUN mkdir -p /data && chown 1000:1000 /data
USER 1000

ENV JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -Xscmx80M -Xshareclasses:name=keycloak"
RUN /bin/sh -c 'java -jar /opt/$JAR &' ; sleep 80 ; ps aux | grep java | grep -v grep | awk '{print $1}' | xargs kill -1

ENV JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -Xquickstart"

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "java", "-jar", "$JAR" ]

