FROM openjdk:13-ea-27-jdk-alpine3.9 as jlink-package

# https://gist.github.com/thomasdarimont/94ab3eb748742d2e793f4f5d32e05932
RUN jlink \
  --no-header-files \
  --no-man-pages \
  --compress=2 \
  --vm=server \
  --exclude-files="**/bin/rmiregistry,**/bin/jrunscript,**/bin/rmid" \
  --add-modules java.base,java.instrument,java.logging,java.management,java.naming,java.scripting,java.se,java.security.jgss,java.security.sasl,java.sql,java.transaction.xa,java.xml,java.xml.crypto,jdk.security.auth,jdk.xml.dom,jdk.unsupported \
  --output /opt/java-runtime

FROM alpine:3.10

ENV JAVA_HOME=/opt/java-runtime
ENV PATH="$PATH:$JAVA_HOME/bin"

COPY --from=jlink-package /opt/java-runtime /opt/java-runtime

