FROM wadahiro/cl4cds as cl4cds

FROM wadahiro/openjdk12-openj9-keycloak

USER root
RUN mkdir -p /javasharedresources && chown 1000:1000 /javasharedresources
USER 1000

RUN env PREPEND_JAVA_OPTS="-Xscmx30M -Xshareclasses:name=keycloak" /bin/sh -c '/opt/jboss/keycloak/bin/standalone.sh &' ; sleep 60 ; ps aux | grep java | grep -v grep | awk '{print $1}' | xargs kill -1

ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -Xscmx30M -Xshareclasses:name=keycloak -Xquickstart"

