FROM wadahiro/cl4cds as cl4cds

FROM wadahiro/keycloak-spring-boot as kc

FROM wadahiro/openjdk12

ARG JAR=spring-boot-keycloak-server-example-undertow-0.0.9.BUILD-SNAPSHOT.jar

COPY --from=kc --chown=1000:1000 /build/spring-boot-keycloak-server-example/target/$JAR /opt/

RUN mkdir -p /javasharedresources && chown 1000:1000 /javasharedresources
RUN mkdir -p /data && chown 1000:1000 /data
USER 1000

COPY --from=cl4cds /cl4cds/src/classes/*.jar /opt/cl4cds.jar

RUN env JAVA_TOOL_OPTIONS="-Xlog:class+load=debug:file=/javasharedresources/keycloak.classtrace" /bin/sh -c 'java -jar /opt/$JAR &' ; sleep 50 ; ps aux | grep java | grep -v grep | awk '{print $1}' | xargs kill -1

RUN java -jar /opt/cl4cds.jar /javasharedresources/keycloak.classtrace /javasharedresources/keycloak.cls

RUN env JAVA_TOOL_OPTIONS="-Xshare:dump -XX:SharedClassListFile=/javasharedresources/keycloak.cls -XX:SharedArchiveFile=/javasharedresources/archive.jsa" java -jar /opt/$JAR

ENV JAVA_TOOL_OPTIONS="-XX:SharedArchiveFile=/javasharedresources/archive.jsa -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "java", "-jar", "$JAR" ]

