FROM wadahiro/openjdk13ea

# Copy from https://github.com/jboss-dockerfiles/keycloak/blob/6.0.1/server/Dockerfile
ENV KEYCLOAK_VERSION 6.0.1
ARG KEYCLOAK_DIST=https://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

RUN apk add --no-cache --virtual .build-deps curl \
    && mkdir -p /opt/jboss \
    && cd /opt/jboss/ \
    && curl -L $KEYCLOAK_DIST | tar zx \
    && mv /opt/jboss/keycloak-?.?.?* /opt/jboss/keycloak \
    && apk del --purge .build-deps

ENV JBOSS_HOME /opt/jboss/keycloak
ENV PROXY_ADDRESS_FORWARDING false

RUN mkdir -p /javasharedresources && chown 1000.1000 /javasharedresources
USER 1000

ENV JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "/opt/jboss/keycloak/bin/standalone.sh" ]
CMD ["-b", "0.0.0.0"]

